server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: EG+qHVHu5HKj9ajdWbQiwP/8+OiO/BVjcoQf+SXTeS9FjLS0qiyghRHkKZoTo5z2
    expiration-time: 86400000
    token-prefix: Bearer
    header-string: Authorization